ore-rates:
  COAL_ORE: 100
  DEEPSLATE_COAL_ORE: 100
  IRON_ORE: 100
  DEEPSLATE_IRON_ORE: 100
  COPPER_ORE: 100
  DEEPSLATE_COPPER_ORE: 100
  GOLD_ORE: 100
  DEEPSLATE_GOLD_ORE: 100
  REDSTONE_ORE: 100
  DEEPSLATE_REDSTONE_ORE: 100
  EMERALD_ORE: 100
  DEEPSLATE_EMERALD_ORE: 100
  LAPIS_ORE: 100
  DEEPSLATE_LAPIS_ORE: 100
  DIAMOND_ORE: 100
  DEEPSLATE_DIAMOND_ORE: 100
  NETHER_GOLD_ORE: 100
  NETHER_QUARTZ_ORE: 100
  ANCIENT_DEBRIS: 100
